# Configuration file for PyISV - Autoencoder

# General settings
device: "cpu"  # Options: "cuda", "cpu"
seed: 42

# Model settings
model:
  type: "autoencoder"  # Options: "autoencoder", "classifier"
  input_shape: [1, 200]  # [Number of channels, Length]
  encoder_channels: [8, 16, 32, 32]
  decoder_channels: [32, 32, 16, 8]
  activation_fn: "ReLU"
  embed_dim: 3

# Training settings
training:
  batch_size: 64
  train_fraction: 0.8
  min_epochs: 1
  max_epochs: 1
  learning_rate: 0.005
  early_stopping:
    patience: 10
    delta: 0.00005
  loss: "MSE"  # Options: "MSE", "RMSE"

# Data settings
input:
  path: "data/RDFs/rdf_images.pt"  # Path for the input dataset for autoencoder
  target_path: null  # Autoencoder uses the same input as target
  normalization: "minmax"  # Options: "minmax", "gaussian"
  padding:
    enabled: false
    final_size: 32

# Output settings
output:
  model_name: "models/best_model.pth"
  log_file: "logs/train_log.txt"
  stats_file: "stats/train_stats.txt"
  normalization_params:
    input_scaler_subval: "norm_vals/input_scaler_subval.npy"
    input_scaler_divval: "norm_vals/input_scaler_divval.npy"
    output_scaler_subval: "norm_vals/output_scaler_subval.npy"
    output_scaler_divval: "norm_vals/output_scaler_divval.npy"